/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountList: typeof import('./src/components/AccountList.vue')['default']
    AccountListHeader: typeof import('./src/components/AccountListHeader.vue')['default']
    AccountListInfo: typeof import('./src/components/AccountListInfo.vue')['default']
    AccountListTable: typeof import('./src/components/AccountListTable.vue')['default']
    Button: typeof import('primevue/button')['default']
  }
}
